import Header from "@/components/header/index";
import "./globals.css";

export const metadata = {
  title: "YoChat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <Header />
        {children}
      </body>
    </html>
  );
}
